// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ewnrojqirpcxcwzltbwq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3bnJvanFpcnBjeGN3emx0YndxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNjEyMDMsImV4cCI6MjA1ODkzNzIwM30.JEXf11hNhmPj30x3zFI9B7MrLeGlskOsoHrxo8DQ6sw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);